/**
 * parse-csv.mjs
 * Reads all CSVs from data_clean/ and writes clean JS data files to src/data/<platform>/real-data.js
 * Run: node scripts/parse-csv.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import Papa from "papaparse";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DATA_CLEAN = resolve(ROOT, "data_clean");
const SRC_DATA = resolve(ROOT, "src/data");

// ─── helpers ──────────────────────────────────────────────────────────────────

function readCSV(path, options = {}) {
  const raw = readFileSync(path, "utf-8").replace(/^\uFEFF/, ""); // strip BOM
  return Papa.parse(raw, {
    header: true,
    skipEmptyLines: true,
    ...options,
  }).data;
}

/** Parse a Spanish-locale percentage string like "22,4%" → 22.4 */
function parseSpanishPct(str) {
  if (!str) return 0;
  return parseFloat(str.toString().replace("%", "").replace(",", ".").trim()) || 0;
}

/** Parse a value that may be "NA", empty, or a number → return number or 0 */
function parseNum(val) {
  if (val === "NA" || val === "" || val == null) return 0;
  return parseFloat(val) || 0;
}

/** Write a JS data file with a const export */
function writeDataFile(filePath, varName, data) {
  const content = `// AUTO-GENERATED by scripts/parse-csv.mjs — do not edit manually\n// Re-run: node scripts/parse-csv.mjs\n\nexport const ${varName} = ${JSON.stringify(data, null, 2)};\n`;
  writeFileSync(filePath, content, "utf-8");
  console.log(`  ✓ wrote ${filePath.replace(ROOT + "/", "")}`);
}

// ─── ISO country code → full name map (for TikTok territories) ───────────────
const ISO_NAMES = {
  MX: "México", US: "United States", CL: "Chile", BR: "Brazil",
  CR: "Costa Rica", DE: "Germany", DO: "Dominican Republic",
  ES: "Spain", FR: "France", GT: "Guatemala", AR: "Argentina",
  CO: "Colombia", EC: "Ecuador", PE: "Peru", CA: "Canada",
  GB: "United Kingdom", IT: "Italy", VE: "Venezuela", UY: "Uruguay",
  BO: "Bolivia", PY: "Paraguay", HN: "Honduras", SV: "El Salvador",
  NI: "Nicaragua", PA: "Panama", CU: "Cuba", PR: "Puerto Rico",
};

// ─── INSTAGRAM ────────────────────────────────────────────────────────────────
console.log("\n📸 Instagram...");

// instagram.csv → daily metrics
const igRaw = readCSV(resolve(DATA_CLEAN, "instagram/instagram.csv"));
const instagramDaily = igRaw.map((row) => ({
  date: row.fecha,
  reach: parseNum(row.alcance),
  videoViews: parseNum(row.views),
  profileViews: parseNum(row.profile_views),
  followersGained: parseNum(row.followers),
  accountsEngaged: parseNum(row.interactions),
  websiteClicks: parseNum(row.link_clicks),
}));

// paises.csv → top countries (skip title row — row 0 is the header row, row 1+ is data)
// PapaParse will use the first data row as headers when header:true
// But paises.csv has a non-header title at row 0. We skip it manually.
function readAudienceCSV(path) {
  const raw = readFileSync(path, "utf-8").replace(/^\uFEFF/, "");
  const lines = raw.split("\n").filter((l) => l.trim());
  // Line 0: title (skip), Line 1: real headers, Line 2+: data
  const withoutTitle = lines.slice(1).join("\n");
  return Papa.parse(withoutTitle, { header: true, skipEmptyLines: true }).data;
}

const paisesRaw = readAudienceCSV(resolve(DATA_CLEAN, "instagram/paises.csv"));
const topCountries = paisesRaw.map((row) => ({
  country: row["Principales países"] || row["Principales pa\u00EDses"] || Object.values(row)[0],
  percentage: parseSpanishPct(Object.values(row)[1]),
})).filter((r) => r.country && r.percentage > 0);

const ciudadesRaw = readAudienceCSV(resolve(DATA_CLEAN, "instagram/ciudades.csv"));
const topCities = ciudadesRaw.map((row) => ({
  city: Object.values(row)[0],
  percentage: parseSpanishPct(Object.values(row)[1]),
})).filter((r) => r.city && r.percentage > 0);

const sexoRaw = readAudienceCSV(resolve(DATA_CLEAN, "instagram/sexo.csv"));
const audienceAgeGender = sexoRaw.map((row) => ({
  ageRange: row["Edad"] || Object.values(row)[0],
  female: parseSpanishPct(row["Mujeres"] || Object.values(row)[1]),
  male: parseSpanishPct(row["Hombres"] || Object.values(row)[2]),
})).filter((r) => r.ageRange);

const igOut = resolve(SRC_DATA, "instagram/real-data.js");
const igContent = `// AUTO-GENERATED by scripts/parse-csv.mjs — do not edit manually
// Re-run: node scripts/parse-csv.mjs

export const instagramDaily = ${JSON.stringify(instagramDaily, null, 2)};

export const topCountries = ${JSON.stringify(topCountries, null, 2)};

export const topCities = ${JSON.stringify(topCities, null, 2)};

export const audienceAgeGender = ${JSON.stringify(audienceAgeGender, null, 2)};
`;
writeFileSync(igOut, igContent, "utf-8");
console.log(`  ✓ wrote src/data/instagram/real-data.js (${instagramDaily.length} daily rows, ${topCountries.length} countries, ${topCities.length} cities, ${audienceAgeGender.length} age groups)`);

// ─── TIKTOK ───────────────────────────────────────────────────────────────────
console.log("\n🎵 TikTok...");

// tiktok.csv → daily metrics
const ttRaw = readCSV(resolve(DATA_CLEAN, "tiktok/tiktok.csv"));
const tiktokDaily = ttRaw.map((row) => ({
  date: row.fecha,
  follower_count: parseNum(row.followers_total),
  followers_gained: parseNum(row.followers_diff),
  play_count: parseNum(row.views),
  profile_views: parseNum(row.profile_views),
  like_count: parseNum(row.likes),
  comment_count: parseNum(row.comments),
  share_count: parseNum(row.shares),
  viewers_total: parseNum(row.viewers_total),
  viewers_new: parseNum(row.viewers_new),
  viewers_returning: parseNum(row.viewers_returning),
})).filter((r) => r.date && r.date !== "NA");

// territory.csv → audience countries
const terrRaw = readCSV(resolve(DATA_CLEAN, "tiktok/territory.csv"));
const audienceCountries = terrRaw
  .filter((r) => r["Top territories"] && r["Top territories"] !== "Others")
  .map((row) => {
    const code = row["Top territories"].trim();
    return {
      country: ISO_NAMES[code] || code,
      percentage: Math.round(parseFloat(row["Distribution"]) * 1000) / 10, // 0.895 → 89.5
    };
  });
// Add Others if present
const othersRow = terrRaw.find((r) => r["Top territories"] === "Others");
if (othersRow) {
  audienceCountries.push({
    country: "Others",
    percentage: Math.round(parseFloat(othersRow["Distribution"]) * 1000) / 10,
  });
}

// gender.csv → audience gender
const genderRaw = readCSV(resolve(DATA_CLEAN, "tiktok/gender.csv"));
const audienceGender = genderRaw.map((row) => ({
  gender: row["Gender"],
  percentage: Math.round(parseFloat(row["Distribution"]) * 1000) / 10,
}));

// activity.csv → active hours (average across all days)
// Format: "23 de febrero", hour 0-23, activeFollowers count
const activityRaw = readCSV(resolve(DATA_CLEAN, "tiktok/activity.csv"));
// Average by hour across all days
const hourTotals = Array(24).fill(0);
const hourCounts = Array(24).fill(0);
for (const row of activityRaw) {
  const hour = parseInt(row["Hour"], 10);
  const val = parseNum(row["Active followers"]);
  if (!isNaN(hour) && hour >= 0 && hour < 24) {
    hourTotals[hour] += val;
    hourCounts[hour] += 1;
  }
}
const audienceActivity = Array.from({ length: 24 }, (_, h) => ({
  hour: h,
  activeFollowers: hourCounts[h] > 0 ? Math.round(hourTotals[h] / hourCounts[h]) : 0,
}));

const ttOut = resolve(SRC_DATA, "tiktok/real-data.js");
const ttContent = `// AUTO-GENERATED by scripts/parse-csv.mjs — do not edit manually
// Re-run: node scripts/parse-csv.mjs

export const tiktokDaily = ${JSON.stringify(tiktokDaily, null, 2)};

export const audienceCountries = ${JSON.stringify(audienceCountries, null, 2)};

export const audienceGender = ${JSON.stringify(audienceGender, null, 2)};

export const audienceActivity = ${JSON.stringify(audienceActivity, null, 2)};
`;
writeFileSync(ttOut, ttContent, "utf-8");
console.log(`  ✓ wrote src/data/tiktok/real-data.js (${tiktokDaily.length} daily rows, ${audienceCountries.length} countries, ${audienceActivity.length} activity hours)`);

// ─── SPOTIFY ──────────────────────────────────────────────────────────────────
console.log("\n🎧 Spotify...");

// spotify.csv → daily account metrics
const spRaw = readCSV(resolve(DATA_CLEAN, "spotify/spotify.csv"));
const spotifyDaily = spRaw.map((row) => ({
  date: row.date,
  listeners: parseNum(row.listeners),
  monthly_listeners: parseNum(row.monthly_listeners),
  monthly_active_listeners: parseNum(row.monthly_active_listeners),
  super_listeners: parseNum(row.super_listeners),
  streams: parseNum(row.streams),
  playlist_adds: parseNum(row.playlist_adds),
  saves: parseNum(row.saves),
  followers: parseNum(row.followers),
}));

// songs.csv → daily per-track streams (wide → structured)
const songsRaw = readCSV(resolve(DATA_CLEAN, "spotify/songs.csv"));
// Strip "-timeline" suffix from column names, fix accent
const TRACK_NAME_MAP = {
  "Caroline-timeline": "Caroline",
  "Cigarettes-timeline": "Cigarettes",
  "Disfruto-timeline": "Disfruto",
  "Get to You-timeline": "Get to You",
  "Marshmallow Heart-timeline": "Marshmallow Heart",
  "Nebula-timeline": "Nebula",
  "Principe turquesa-timeline": "Príncipe turquesa",
  "Residuos de una voz-timeline": "Residuos de una voz",
};
const trackNames = Object.values(TRACK_NAME_MAP);

const songsTimeline = songsRaw.map((row) => {
  const entry = { date: row.date };
  for (const [rawKey, cleanName] of Object.entries(TRACK_NAME_MAP)) {
    entry[cleanName] = parseNum(row[rawKey]);
  }
  return entry;
});

// Precompute total streams per track (over all time, for reference)
const trackTotals = trackNames.map((name) => ({
  title: name,
  streams: songsTimeline.reduce((sum, row) => sum + (row[name] || 0), 0),
})).sort((a, b) => b.streams - a.streams);

const spOut = resolve(SRC_DATA, "spotify/real-data.js");
const spContent = `// AUTO-GENERATED by scripts/parse-csv.mjs — do not edit manually
// Re-run: node scripts/parse-csv.mjs

export const spotifyDaily = ${JSON.stringify(spotifyDaily, null, 2)};

export const songsTimeline = ${JSON.stringify(songsTimeline, null, 2)};

export const trackNames = ${JSON.stringify(trackNames, null, 2)};

export const trackTotals = ${JSON.stringify(trackTotals, null, 2)};
`;
writeFileSync(spOut, spContent, "utf-8");
console.log(`  ✓ wrote src/data/spotify/real-data.js (${spotifyDaily.length} daily rows, ${songsTimeline.length} song rows, ${trackNames.length} tracks)`);

console.log("\n✅ All CSV data parsed and written successfully.\n");
